SusceptibleMaskItems = {
--- Hazmat Suits ---
	HazmatSuit =                                          { durability=300 },
	MysteriousHazmat =                                    { durability=300 },    
	CEDAHazmatSuit =                                      { durability=300 },    
	HazmatSuitCEDANoShoes =                               { durability=300 },    
	CEDAHazmatSuitBlack =                                 { durability=300 },    
	CEDAHazmatSuitBlackNoShoes =                          { durability=300 },    
	CEDAHazmatSuitBlue =                                  { durability=300 },    
	CEDAHazmatSuitBlueNoShoes =                           { durability=300 },    
	CEDAHazmatSuitRed =                                   { durability=300 },    
	CEDAHazmatSuitRedNoShoes =                            { durability=300 },    
	NBHHazmatSuit =                                       { durability=300 },    
	NBHHazmatSuitNoShoes =                                { durability=300 },
	HazmatSuit2 =                                         { durability=300 },        
	HazmatSuit2NoShoes =                                  { durability=300 },
	Hat_M17Doff =                                         { durability=300 },
	Hat_M40Doff =                                         { durability=300 },

--- Gas masks ---
	Hat_GasMask =                                         { durability=200 },
	Hat_NBCmask =                                         { durability=200 },
	Hat_SwatGasMask =                                     { durability=200 },
	Hat_FM53 =                                            { durability=200 },
	Hat_M17 =                                             { durability=200 },
	Hat_M40 =                                             { durability=200 },    
	Hat_M45_GasMask =                                     { durability=200 },
	Hat_M50 =                                             { durability=200 },
	Hat_PoliceM17 =                                       { durability=200 },
	Hat_Mask_Cloth =                                      { durability=200 },
	Hat_Mask_Half =                                       { durability=200 },
	Hat_Maska =                                           { durability=200 },
	Hat_MCU_GasMask =                                     { durability=200 },
	Hat_MSA_Gas_Mask =                                    { durability=200 },
	Hat_MSA_Gas_Mask_AMP =                                { durability=200 },
	Hat_Riot_Visor =                                      { durability=200 },
	Hat_PSGT_Visor =                                      { durability=200 },
	Hat_MX_Helmet =                                       { durability=200 },
	Hat_Killa =                                           { durability=200 },
	Hat_Killa_Visor =                                     { durability=200 },
	Hat_HGU56 =                                           { durability=200 },
	Hat_HGU56_Visor =                                     { durability=200 },
	Hat_Ghost =                                           { durability=200 },
	Hhunk =                                               { durability=200 },
	Mhunk2 =                                              { durability=200 },
	Mhunk3 =                                              { durability=200 },
	Hage =                                                { durability=200 },
	HWhatup =                                             { durability=200 },    
	HWhatdown =                                           { durability=200 },
	Mask_HECU  =                                          { durability=200 },    
	GP5GasMask  =                                         { durability=200 },
 	Ranger_Advanced_Helmet  =                             { durability=200 },
	Ranger_Desert_Helmet  =                               { durability=200 },    
	Ranger_Elite_Helmet  =                                { durability=200 },
	Ranger_Riot_Helmet  =                                 { durability=200 }, 
	Ranger_Veteran_Helmet  =                              { durability=200 },
 	Ranger_Winter_Helmet  =                               { durability=200 }, 
  	
 --- Enclosed Military Helmets ---   
	Hat_KillaHelmet =                                     { durability=190 },
	Hat_880_Helmet =                                      { durability=190 },
	Hat_880_Visor =                                       { durability=190 },
	Hat_PSGT_Helmet_Camo =                                { durability=190 },
	Hat_Face_Shield =                                     { durability=190 },

--- Unique Mod gas masks ---
	NomadMask =                                           { durability=180 },
	OminousNomadMask =                                    { durability=180 },
	PrepperMask =                                         { durability=180 },
	StalkerMask =                                         { durability=180 },
	RogueMask =                                           { durability=180 },
	ClericMask =                                          { durability=180 },	
	Hat_Rebreather =                                      { durability=180 },
	Mjill =                                               { durability=180 },    

--- Surgical, dust and face masks ---
	Hat_SurgicalMask_Blue =                               { durability=120 },
	Hat_SurgicalMask_Green =                              { durability=120 },
	Hat_DustMask =                                        { durability=120 },
	Hat_DisposableMask_White =                            { durability=120 },
	Hat_DisposableMask_Black =                            { durability=120 },        
	Hat_SpiffoMask_Black =                                { durability=120 },    
	Hat_SpiffoMask_White =                                { durability=120 },        
	Hat_SpiffoMask_Yellow =                               { durability=120 },
	Hat_XMaskWhite =                                      { durability=120 },    
	Hat_XMaskBlack =                                      { durability=120 },    
	Hat_XMaskBlack_Red =                                  { durability=120 },        
	Hat_SmileMaskYellow =                                 { durability=120 },
	Hat_SmileMaskBlack =                                  { durability=120 },    
	Hat_HalloweenMask1 =                                  { durability=120 },    
	Hat_FaceMaskBlack =                                   { durability=120 },        
	Hat_FaceMaskYellow =                                  { durability=120 },
	Hat_FaceMaskNavy =                                    { durability=120 },
	Hat_FaceMaskWhite =                                   { durability=120 },    
	Hat_AdidasFaceMask_Black =                            { durability=120 },    
	Hat_AdidasFaceMask_White =                            { durability=120 },        
	Hat_WoodlandFaceMask =                                { durability=120 },        
 
--- Basic face covering helmets/headgear --- 
	Hat_CrashHelmetFULL =                                 { durability=90 },
	Hat_RiotHelmet =                                      { durability=90 },
	Hat_MilitaryHelmetRiot =                              { durability=90 },
	Hat_PoliceRiotHelmet =                                { durability=90 },
	Hat_SWATRiotHelmet2 =                                 { durability=90 },
	Hat_Antibombhelmet =                                  { durability=90 },
	WeldingMask =                                         { durability=90 },
	Hat_TagillaMask =                                     { durability=90 },
	Hat_TagillaMask2 =                                    { durability=90 },
	Hat_MotorcycleHelmet2 =                               { durability=90 },
	Hat_WelderMask2 =                                     { durability=90 },
	Shroud_Black =                                        { durability=90 },
	Full_Helmet_UN =                                      { durability=90 },
	Full_Helmet_Smiley =                                  { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalBobaFett =           { durability=90 },
	Hat_AuthenticCrashHelmetFULLEvelKnievel =             { durability=90 },
	Hat_AuthenticCrashHelmetFULLGreenDragon =             { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalKiss =               { durability=90 },
	Hat_AuthenticCrashHelmetFULLOptimus =                 { durability=90 },
	Hat_AuthenticCrashHelmetFULLPowerRangerRed    =       { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalShark =              { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalSnowLeopard =        { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalVenom =              { durability=90 },
	Hat_AuthenticCrashHelmetFULLDecalSimple =             { durability=90 },
	Hat_AuthenticCrashHelmetFULLRacing =                  { durability=90 },
	Hat_AuthenticCrashHelmetFULLTINT =                    { durability=90 },

--- Bandanas & cloth masks ---
	Hat_BandanaMask =                                     { durability=26 },
	Hat_Balaclava_Swat =                                  { durability=26 },
	Hat_PoliceBalaclava =                                 { durability=26 },
	Hat_JasonSack =                                       { durability=26 },
	Hat_LeatherFace    =                                  { durability=26 },
	Hat_MichaelMyers =                                    { durability=26 },
	Bandana_Clown =                                       { durability=26 },
	Bandana_Mexico =                                      { durability=26 },
	Bandana_Germany =                                     { durability=26 },
	Bandana_USA =                                         { durability=26 },
	Hat_BandanaMaskDesert =                               { durability=26 },
	Hat_BandanaMaskRed =                                  { durability=26 },
	SkullHalfMask =                                       { durability=26 },
	Legion_Bandana_Black =                                { durability=26 },
	Legion_Bandana_Red =                                  { durability=26 },
	Legion_Bandana_Black_Ohio =                           { durability=26 },
	Legion_Bandana_Red_Ohio =                             { durability=26 },
	Legion_Bandana_Blue_Ohio =                            { durability=26 },
	Hat_Shemagh =                                         { durability=26 },
	Hat_ShemaghDesert =                                   { durability=26 },
	Hat_ShemaghWoodland =                                 { durability=26 },
	Hat_BandanaMaskTINT =                                 { durability=26, quality=1 },
	ClothMask =                                           { durability=26, quality=1 },

--- Not implemented ---
	Hat_GasMask_Improvised =                              { durability=24 },
	HCImprovisedgasmask =                                 { durability=24 },
	HCImprovisedhazmat =                                  { durability=24 },
    
--- Novelty masks & hats ---    
	Hat_TrueEyeCult =                                     { durability=5 },
	Hat_GhostFace =                                       { durability=5 },
	Hat_DRLegoHead =                                      { durability=5 },
	Hat_DeathMask =                                       { durability=5 }
    
}
