SusceptibleMaskItems = {
-- Hazmat suits + Doffs
    HazmatSuit =              							{ drainCap=300 },
	MysteriousHazmat =		  							{ drainCap=300 },	
	CEDAHazmatSuit =		  							{ drainCap=300 },	
	HazmatSuitCEDANoShoes =	  							{ drainCap=300 },	
	CEDAHazmatSuitBlack =	  							{ drainCap=300 },	
	CEDAHazmatSuitBlackNoShoes =	  					{ drainCap=300 },	
	CEDAHazmatSuitBlue =	  							{ drainCap=300 },	
	CEDAHazmatSuitBlueNoShoes =	  						{ drainCap=300 },	
	CEDAHazmatSuitRed =	  	  							{ drainCap=300 },	
	CEDAHazmatSuitRedNoShoes =	  						{ drainCap=300 },	
	NBHHazmatSuit =	  		  							{ drainCap=300 },	
	NBHHazmatSuitNoShoes =	  							{ drainCap=300 },
    HazmatSuit2 =	  		  							{ drainCap=300 },		
	HazmatSuit2NoShoes =	  							{ drainCap=300 },
    Hat_M17Doff =         								{ drainCap=300 },
    Hat_M40Doff =         								{ drainCap=300 },

-- Gas Masks + Gas mask enclosed helmets
    Hat_GasMask =             							{ drainCap=200 },
    Hat_NBCmask =             							{ drainCap=200 },
	Hat_SwatGasMask =         							{ drainCap=200 },
    Hat_FM53 =                							{ drainCap=200 },
    Hat_M17 =         									{ drainCap=200 },
    Hat_M40 =         									{ drainCap=200 },	
    Hat_M45_GasMask =         							{ drainCap=200 },
    Hat_M50 =                 							{ drainCap=200 },
	Hat_PoliceM17 =           							{ drainCap=200 },
    Hat_Mask_Cloth =          							{ drainCap=200 },
    Hat_Mask_Half =           							{ drainCap=200 },
    Hat_Maska =               							{ drainCap=200 },
    Hat_MCU_GasMask =         							{ drainCap=200 },
    Hat_MSA_Gas_Mask =        							{ drainCap=200 },
    Hat_MSA_Gas_Mask_AMP =    							{ drainCap=200 },
    Hat_Riot_Visor =          							{ drainCap=200 },
    Hat_PSGT_Visor =          							{ drainCap=200 },
    Hat_MX_Helmet =           							{ drainCap=200 },
    Hat_Killa =               							{ drainCap=200 },
    Hat_Killa_Visor =         							{ drainCap=200 },
    Hat_HGU56 =               							{ drainCap=200 },
    Hat_HGU56_Visor =         							{ drainCap=200 },
    Hat_Ghost =               							{ drainCap=200 },
	Hhunk =               	  							{ drainCap=200 },
	Mhunk2 =             	  							{ drainCap=200 },
	Mhunk3 =             	  							{ drainCap=200 },
	Hage =              	  							{ drainCap=200 },
    HWhatup =                 							{ drainCap=200 },	
	HWhatdown =          	  							{ drainCap=200 },
    Mask_HECU  =              							{ drainCap=200 },	
    GP5GasMask  =              							{ drainCap=200 },	

-- 	Enclosed military helmets
    Hat_KillaHelmet =         							{ drainCap=190 },
	Hat_880_Helmet =          							{ drainCap=190 },
    Hat_880_Visor =           							{ drainCap=190 },
    Hat_PSGT_Helmet_Camo =    							{ drainCap=190 },
    Hat_Face_Shield =         							{ drainCap=190 },

-- Unique mod gas masks
    NomadMask =               							{ drainCap=180 },
    OminousNomadMask =        							{ drainCap=180 },
    PrepperMask =             							{ drainCap=180 },
    StalkerMask =             							{ drainCap=180 },
	RogueMask =               							{ drainCap=180 },
	ClericMask =          		  						{ drainCap=180 },	
	Hat_Rebreather =          							{ drainCap=180 },
	Mjill =          		  							{ drainCap=180 },	

-- Medical Masks & Dust Masks (and mod face masks)
    Hat_SurgicalMask_Blue =   							{ drainCap=120 },
    Hat_SurgicalMask_Green =  							{ drainCap=120 },
    Hat_DustMask =            							{ drainCap=120 },
	Hat_DisposableMask_White =            				{ drainCap=120 },
	Hat_DisposableMask_Black =            				{ drainCap=120 },		
	Hat_SpiffoMask_Black =            					{ drainCap=120 },	
	Hat_SpiffoMask_White =            					{ drainCap=120 },		
	Hat_SpiffoMask_Yellow =            					{ drainCap=120 },
	Hat_XMaskWhite =            						{ drainCap=120 },	
	Hat_XMaskBlack =            						{ drainCap=120 },	
	Hat_XMaskBlack_Red =            					{ drainCap=120 },		
	Hat_SmileMaskYellow =            					{ drainCap=120 },
	Hat_SmileMaskBlack =            					{ drainCap=120 },	
	Hat_HalloweenMask1 =            					{ drainCap=120 },	
	Hat_FaceMaskBlack =            						{ drainCap=120 },		
	Hat_FaceMaskYellow =            					{ drainCap=120 },
	Hat_FaceMaskNavy =            						{ drainCap=120 },
	Hat_FaceMaskWhite =            						{ drainCap=120 },	
	Hat_AdidasFaceMask_Black =            				{ drainCap=120 },	
	Hat_AdidasFaceMask_White =            				{ drainCap=120 },		
	Hat_WoodlandFaceMask =            					{ drainCap=120 },		

-- Riot Helmets,Crash Helmets & Welding Masks	
    Hat_CrashHelmetFULL =     							{ drainCap=90 },
    Hat_RiotHelmet =          							{ drainCap=90 },
	Hat_MilitaryHelmetRiot =   							{ drainCap=90 },
	Hat_PoliceRiotHelmet =    							{ drainCap=90 },
	Hat_SWATRiotHelmet2 =     							{ drainCap=90 },
	Hat_Antibombhelmet =      							{ drainCap=90 },
    WeldingMask =             							{ drainCap=90 },
	Hat_TagillaMask =         							{ drainCap=90 },
	Hat_TagillaMask2 =        							{ drainCap=90 },
	Hat_MotorcycleHelmet2 =    							{ drainCap=90 },
	Hat_WelderMask2 =         							{ drainCap=90 },
	Shroud_Black =										{ drainCap=90 },
	Full_Helmet_UN =		  				 			{ drainCap=90 },
	Full_Helmet_Smiley =	  							{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalBobaFett =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLEvelKnievel =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLGreenDragon =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalKiss =				{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLOptimus =				{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLPowerRangerRed	=    	{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalShark =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalSnowLeopard =		{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalVenom =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLDecalSimple =			{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLRacing =				{ drainCap=90 },
	Hat_AuthenticCrashHelmetFULLTINT =					{ drainCap=90 },

-- Bandanas
	Hat_BandanaMask =         							{ drainCap=26 },
	Hat_Balaclava_Swat =      							{ drainCap=26 },
	Hat_PoliceBalaclava =     							{ drainCap=26 },
	Hat_JasonSack =			  							{ drainCap=26 },
	Hat_LeatherFace	=		  							{ drainCap=26 },
	Hat_MichaelMyers =		  							{ drainCap=26 },
	Bandana_Clown =         	  						{ drainCap=26 },
	Bandana_Mexico =         	  						{ drainCap=26 },
	Bandana_Germany =         	  						{ drainCap=26 },
	Bandana_USA =         	 	  						{ drainCap=26 },
	Hat_BandanaMaskDesert =   							{ drainCap=26 },
	Hat_BandanaMaskRed =      							{ drainCap=26 },
	SkullHalfMask =           							{ drainCap=26 },
	Legion_Bandana_Black =   							{ drainCap=26 },
	Legion_Bandana_Red =      							{ drainCap=26 },
	Legion_Bandana_Black_Ohio =           				{ drainCap=26 },
	Legion_Bandana_Red_Ohio =   						{ drainCap=26 },
	Legion_Bandana_Blue_Ohio =      					{ drainCap=26 },		
	Hat_Shemagh =   									{ drainCap=26 },
	Hat_ShemaghDesert =      							{ drainCap=26 },
	Hat_ShemaghWoodland =   							{ drainCap=26 },
    Hat_BandanaMaskTINT =     							{ drainCap=26, quality=1 },
	ClothMask =         								{ drainCap=26, quality=1 },	

-- Improvised masks (not implemented)
    Hat_GasMask_Improvised = 						 	{ drainCap=24 },
    HCImprovisedgasmask =     							{ drainCap=24 },
    HCImprovisedhazmat =      							{ drainCap=24 },
	
-- Mod novelty masks	
	Hat_TrueEyeCult =         							{ drainCap=5 },
	Hat_GhostFace =           							{ drainCap=5 },
	Hat_DRLegoHead =          							{ drainCap=5 },
	Hat_DeathMask =           							{ drainCap=5 }
	
}
